<a href="https://colab.research.google.com/github/mnngit/Data_Science-ML/blob/main/titanic_predict_without_using_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pickle
import numpy as np

#  **Prevent Google Colab from frequently disconnection** 

In [ ]:
# function ConnectButton(){
#     console.log("Working");

#     document.querySfelector("#connect").click()
# }

# setInterval(ConnectButton,60000)

# **Mounting Google Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
ohe_sex = pickle.load(open('/content/drive/MyDrive/100DML/models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('/content/drive/MyDrive/100DML/models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('/content/drive/MyDrive/100DML/models/clf.pkl','rb'))

In [ ]:
# assume user input
# Pclass 	Sex 	Age 	SibSp 	Parch 	Fare 	Embarked
# 1 	male 	45.5 	0 	0 	28.5000 	S
test_input = np.array([2,'male', 31, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [ ]:
test_input

array([[2, 'male', 31, 0, 0, 10.5, 'S']], dtype=object)

In [ ]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
test_input_sex

array([[0., 1.]])

In [ ]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [ ]:
test_input_embarked

array([[0., 0., 1.]])

In [ ]:
test_input_age = test_input[:,2].reshape(1, 1)

In [ ]:
test_input_age

array([[31]], dtype=object)

In [ ]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]], test_input_age, test_input_sex, test_input_embarked), axis=1)

In [24]:
test_input_transformed.shape

(1, 10)

In [25]:
clf.predict(test_input_transformed)

array([1])